#!/bin/bash

echo "======================================"
echo "Address Book - Deployment Setup"
echo "======================================"
echo ""
echo "Generating NEXTAUTH_SECRET..."
echo ""

SECRET=$(openssl rand -base64 32)

echo "Your NEXTAUTH_SECRET (copy this):"
echo ""
echo "$SECRET"
echo ""
echo "======================================"
echo ""
echo "Next Steps for DigitalOcean Deployment:"
echo ""
echo "1. Push code to GitHub:"
echo "   git init"
echo "   git add ."
echo "   git commit -m 'Initial commit: Address book app'"
echo "   git branch -M main"
echo "   git remote add origin https://github.com/YOUR_USERNAME/YOUR_REPO.git"
echo "   git push -u origin main"
echo ""
echo "2. Go to: https://cloud.digitalocean.com/apps"
echo ""
echo "3. Click 'Create App' → Select GitHub"
echo ""
echo "4. Configure:"
echo "   - Build: npm ci && npx prisma generate && npx prisma migrate deploy && npm run build"
echo "   - Run: npm start"
echo "   - Port: 3000"
echo ""
echo "5. Add Environment Variables:"
echo "   - NODE_ENV = production"
echo "   - NEXTAUTH_SECRET = $SECRET (mark as Secret)"
echo "   - DATABASE_URL = file:/data/sqlite.db"
echo "   - NEXTAUTH_URL = (leave empty, update after first deploy)"
echo ""
echo "6. After first deploy, update NEXTAUTH_URL with your app URL"
echo ""
echo "======================================"
